(deftheme my-wheatgrass
  "Created 2013-08-16.")

(custom-theme-set-faces
 'my-wheatgrass
 '(cursor ((((class color) (min-colors 89)) (:background "orange"))))
 '(error ((((class color) (min-colors 89)) (:foreground "salmon1"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "orange"))))
 '(success ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "dark green"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "dark goldenrod"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "SpringGreen4"))))
 '(highlight ((t (:background "#C0C0C0" :foreground "black"))))
 ;; '(region ((t (:background "SteelBlue4"))))
 '(region ((t (:background "#555753"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "dark slate gray"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "white" :background "dark goldenrod"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "gray25"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightSteelBlue"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "SpringGreen3"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "turquoise"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#f92672"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "aquamarine"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "cyan"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "dark cyan"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:weight normal :foreground "yellow green"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "pale turquoise"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "dark sea green"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "dark turquoise"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "yellow green"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "dark khaki"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "pale turquoise"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "pale green"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "SpringGreen3"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "deep sky blue"))))
 ;; '(default ((((class color) (min-colors 89)) (:foreground "wheat" :background "black"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#f0f0f0" :background "black"))))
 '(show-paren-match ((t (:foreground "black" :foreground "red" :weight bold))))
 '(hl-line ((t (:background "#232526"))))
 '(ac-gtags-selection-face ((t (:background "navy"))))
 '(ac-yasnippet-candidate-face ((t nil)))
 ;; '(bold-italic ((t (:slant italic :weight bold :family "Fira Sans"))))
 ;; '(italic ((t (:slant italic :family "Fira Sans"))))
 ;; '(bold-italic ((t (:slant italic :weight bold :family "DejaVu Sans"))))
 ;; '(italic ((t (:slant italic :family "DejaVu Sans"))))
 '(bold-italic ((t (:slant italic :weight bold :family "Source Sans Pro"))))
 '(italic ((t (:slant italic :family "Source Sans Pro"))))
 ;; '(bold-italic ((t (:slant italic :weight bold :family "Helvetica Neue"))))
 ;; '(italic ((t (:slant italic :family "Helvetica Neue"))))
 '(preview-reference-face ((t (:background "white" :foreground "black"))))
 '(show-paren-match ((t (:foreground "red" :weight bold))))
 '(mode-line ((((class color) (min-colors 89)) (:background "gray19" :foreground "cornflower blue" :box (:line-width -1 :style released-button)))))
 )

(provide-theme 'my-wheatgrass)
